version: "3.9"

services:
  potgres_db:
    image: postgres:15
    container_name: drf_lesson_docker
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  drf_lesson_1:
    build:
      context: .
    container_name: drf_lesson_django
    depends_on:
      - potgres_db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py makemigrations && ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

volumes:
  pg_data:
  static_volume:
  media_volume:
