name: drf_lesson_1
on: push
jobs:
  first:
    name: Install Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt-get update
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install python3-pip
        run: sudo apt-get install python3-pip
      - name: Requirements install
        run: pip install -r requirements.txt
      - name: Run test
        env:
          DJANGO_SETTINGS_MODULE: core.settings.local
          SECRET_KEY: django-insecure-bg!v#&p_5-8py*&0=jni8o@99e*1jz6_it$o!7ptx0ehw5)(_u
        run: python manage.py test
